[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evmVersion = "cancun"

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts",
    "@chainlink/contracts=lib/chainlink/contracts",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
