[profile.default]
src = "contracts"
out = "out"
libs = ["dependencies"]
evmVersion = "cancun"
gas_reports = ["TermMaxMarket", "GearingTokenWithERC20", "TermMaxRouter"]
viaIR = true
optimizer = true
optimizer_runs = 200
ffi = true

fs_permissions = [
    { access = "read", path = "test/testdata" },
    { access = "read", path = "script/deploy/deploydata" },
    { access = "read-write", path = "deployments" }
]

[soldeer]
# whether soldeer manages remappings
remappings_generate = true

# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false

# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = true

# a prefix to add to the remappings ("@" would give `@name`)
remappings_prefix = ""

# where to store the remappings ("txt" for `remappings.txt` or "config" for `foundry.toml`)
# ignored when `soldeer.toml` is used as config (uses `remappings.txt`)
remappings_location = "txt"


[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.2.0"
"@openzeppelin-contracts-upgradeable" = "5.2.0"
"@chainlink-contracts" = "1.2.0"
"@uniswap-v3-core" = "1.0.2-solc-0.8-simulate"
"@uniswap-v3-periphery" = "1.4.4"
pendle-core-v2 = { version = "1.0.0", git = "https://github.com/pendle-finance/pendle-core-v2-public.git", rev = "d6126bde7bbd9da521f16d561931ddf90515bf69" }
metamorpho = { version = "1.0.0", git = "https://github.com/morpho-org/metamorpho.git", rev = "00da9ad27da8051bce663eeac02f3b9c0c0aa8d8" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
