[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
evmVersion = "cancun"
gas_reports = ["TermMaxMarket", "GearingTokenWithERC20", "TermMaxRouter"]
viaIR = true
optimizer = true
optimizer_runs = 200
ffi = true

[dependencies]
openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v5.0.2" }
openzeppelin-contracts-upgradeable = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable.git", tag = "v5.0.2" }
chainlink = { git = "https://github.com/smartcontractkit/chainlink.git", tag = "v2.17.0" }
pendle-core-v2 = { git = "https://github.com/pendle-finance/pendle-core-v2-public.git", rev = "d6126bde7bbd9da521f16d561931ddf90515bf69" }
uniswap-v3-core = { git = "https://github.com/Uniswap/v3-core.git", tag = "v1.0.0" }
uniswap-v3-periphery = { git = "https://github.com/Uniswap/v3-periphery.git", tag = "v1.3.0" }
forge-std = { git = "https://github.com/foundry-rs/forge-std.git", tag = "v1.9.6" }
metamorpho = { git = "https://github.com/morpho-org/metamorpho.git", tag = "v1.0.0" }

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts",
    "@chainlink/contracts=lib/chainlink/contracts",
    "@pendle/core-v2/contracts=lib/pendle-core-v2-public/contracts",
    "@uniswap/v3-core/contracts=lib/v3-core/contracts",
    "@uniswap/v3-periphery/contracts=lib/v3-periphery/contracts",
    "forge-std=lib/forge-std/src"
]

fs_permissions = [
    { access = "read", path = "test/testdata" },
    { access = "read", path = "script/deploy/deploydata" },
    { access = "read-write", path = "deployments" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
